CREATE TABLE IF NOT EXISTS user_profile_extras (
    user_id INT PRIMARY KEY,
    instagram VARCHAR(255) NULL,
    linkedin VARCHAR(255) NULL,
    github VARCHAR(255) NULL,
    website VARCHAR(255) NULL,
    resume_path VARCHAR(512) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
